import 'package:riverpod_annotation/riverpod_annotation.dart';
import '../../data/repositories/schedule_repository_impl.dart';
import '../../domain/entities/schedule_entity.dart';
import '../../domain/usecases/get_schedules_usecase.dart';

part 'schedule_provider.g.dart';

@riverpod
class Schedules extends _$Schedules {
  @override
  Stream<List<ScheduleEntity>> build() {
    final useCase = ref.watch(getSchedulesUseCaseProvider);
    return useCase.execute();
  }

  Future<void> createSchedule({
    required String title,
    String? details,
    String? location,
    required DateTime startTime,
    required DateTime endTime,
  }) async {
    final repository = ref.read(scheduleRepositoryProvider);
    
    final newSchedule = ScheduleEntity(
      id: '',  // Will be generated by data source
      title: title,
      details: details,
      location: location,
      startTime: startTime,
      endTime: endTime,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    );

    await repository.createSchedule(newSchedule);
  }

  Future<void> updateSchedule(ScheduleEntity schedule) async {
    final repository = ref.read(scheduleRepositoryProvider);
    await repository.updateSchedule(schedule);
  }

  Future<void> deleteSchedule(String id) async {
    final repository = ref.read(scheduleRepositoryProvider);
    await repository.deleteSchedule(id);
  }
}
